# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='\u4e0a\u4f20\u7528\u6237\u540d')),
                ('filename', models.FileField(upload_to='upload', verbose_name='Excel\u6587\u4ef6')),
            ],
        ),
        migrations.CreateModel(
            name='ImeiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=50)),
                ('state', models.CharField(default='unfinished', max_length=20)),
                ('starttime', models.DateTimeField(default=datetime.datetime.now)),
                ('oktime', models.DateTimeField(null=True)),
            ],
        ),
    ]
